const EL='https://api.elevenlabs.io';
const cors=(origin,env)=>({'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN==='*'?'*':env.ALLOWED_ORIGIN||origin,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'});
const json=(body,status,origin,env)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json',...cors(origin,env)}});
export default{async fetch(req,env){const origin=req.headers.get('Origin')||'';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin,env)});if(!env.ELEVENLABS_API_KEY)return json({error:'The ElevenLabs API key has not been configured on the Worker.'},500,origin,env);const u=new URL(req.url);try{
 if(env.OPALREADER_ACCESS_TOKEN&&req.headers.get('X-OpalReader-Token')!==env.OPALREADER_ACCESS_TOKEN)return json({error:'The personal access token is missing or incorrect.'},401,origin,env);
 if(u.pathname==='/api/voices'&&req.method==='GET'){const q=new URLSearchParams(u.search);q.set('include_total_count','true');const r=await fetch(`${EL}/v2/voices?${q}`,{headers:{'xi-api-key':env.ELEVENLABS_API_KEY}});return new Response(r.body,{status:r.status,headers:{'Content-Type':'application/json',...cors(origin,env)}})}
 if(u.pathname==='/api/shared-voices'&&req.method==='GET'){const r=await fetch(`${EL}/v1/shared-voices?${u.searchParams}`,{headers:{'xi-api-key':env.ELEVENLABS_API_KEY}});return new Response(r.body,{status:r.status,headers:{'Content-Type':'application/json',...cors(origin,env)}})}
 if(u.pathname==='/api/shared-voices/add'&&req.method==='POST'){const b=await req.json();if(!b.public_user_id||!b.voice_id)return json({error:'Shared voice owner and ID are required.'},400,origin,env);const r=await fetch(`${EL}/v1/voices/add/${encodeURIComponent(b.public_user_id)}/${encodeURIComponent(b.voice_id)}`,{method:'POST',headers:{'xi-api-key':env.ELEVENLABS_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({new_name:b.new_name||'OpalReader voice',bookmarked:true})});return new Response(r.body,{status:r.status,headers:{'Content-Type':'application/json',...cors(origin,env)}})}
 if(u.pathname==='/api/speech'&&req.method==='POST'){const b=await req.json();if(!b.voice_id||!b.text)return json({error:'Voice and text are required.'},400,origin,env);if(b.text.length>40000)return json({error:'This chapter is too long for one V1 generation request. Split it before generating.'},413,origin,env);const format=b.output_format||'mp3_44100_128';const r=await fetch(`${EL}/v1/text-to-speech/${encodeURIComponent(b.voice_id)}/stream?output_format=${encodeURIComponent(format)}`,{method:'POST',headers:{'xi-api-key':env.ELEVENLABS_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({text:b.text,model_id:b.model_id||'eleven_multilingual_v2'})});return new Response(r.body,{status:r.status,headers:{'Content-Type':r.headers.get('Content-Type')||'audio/mpeg',...cors(origin,env)}})}
 return json({error:'Not found'},404,origin,env)}catch(e){return json({error:e.message||'Upstream request failed.'},502,origin,env)}}};
